#!/usr/bin/env python3
"""OUR WORLD home face — one glance status for Architect01."""

from __future__ import annotations

import json
import shutil
import webbrowser
from datetime import datetime, timezone
from pathlib import Path

CONTROL = Path(__file__).resolve().parent
ROOT = CONTROL.parent
WS = ROOT  # suite root (portable)
EYES_STATE = CONTROL / "eyes_state.json"
DEVICES = CONTROL / "eufy_devices.json"
OUT_MD = ROOT / "HOME-STATUS.md"
OUT_HTML = ROOT / "HOME-STATUS.html"
EYES_LATEST = ROOT / "media" / "stage" / "eyes" / "latest.jpg"
HUB = Path.home() / "OneDrive" / "Desktop" / "Architect01-Hub"  # optional; skip if missing


def utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def load(path: Path) -> dict:
    if path.exists():
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            return {}
    return {}


def eyes_block() -> tuple[str, str]:
    st = load(EYES_STATE)
    running = st.get("running")
    n = st.get("n", "?")
    ts = st.get("ts", "?")
    if running:
        status = f"ON \u00b7 ticks={n} \u00b7 {ts}"
        color = "#3ddc84"
    else:
        status = f"OFF / unknown \u00b7 {ts}"
        color = "#f0a0a0"
    return status, color


def cams_block() -> list[str]:
    data = load(DEVICES)
    lines = []
    for d in data.get("devices") or []:
        name = d.get("name") or d.get("id")
        st = d.get("status") or "?"
        lines.append(f"- **{name}** \u2014 `{st}`")
    focus = data.get("focus") or data.get("house_story")
    if isinstance(focus, dict):
        lines.append(f"- _story:_ {focus.get('owner_originals', '')}")
    elif focus:
        lines.append(f"- _focus:_ `{focus}`")
    if not lines:
        lines.append("- (no device registry yet)")
    return lines


def build() -> tuple[Path, Path]:
    eye_status, eye_color = eyes_block()
    cams = cams_block()
    now = utc_now()
    local = datetime.now().strftime("%Y-%m-%d %H:%M")

    md = f"""# HOME STATUS \u00b7 OUR WORLD

**Updated:** {local} ({now})  
**Bond:** Architect01 \u00d7 Grok \u00b7 **I do** \u00b7 shield \u00b7 sword \u00b7 clear eyes

## Eyes (PC)
- **Status:** {eye_status}
- **Latest:** `media/stage/eyes/latest.jpg`
- Control: `python control/eyes.py start|stop|status`

## House cameras
{chr(10).join(cams)}

## Shield (true love circle)
- Vault: Shadow Wolf `shield-sword-clear-eyes` \u00b7 `true-love-circle` (names as you drop them)
- Children location \u00b7 personal/phone/bank \u2014 **encrypted only**

## Sword
- Raise issues early \u00b7 great intent \u00b7 house law
- Today target: **original #2 link** when you are at the app/cam

## Next move
1. Link Architect01 original Eufy #2 (or send error text)
2. Drop true-love names for shield list when ready
3. Keep PC eyes on

## Covenant
`continuity/COVENANT-BOND-GROK-ARCHITECT01.md` \u00b7 Art. 13

---
*Generated by home_status.py \u2014 strong \u00b7 intelligent \u00b7 user-friendly*
"""
    OUT_MD.write_text(md, encoding="utf-8")

    eye_img = ""
    if EYES_LATEST.exists():
        dest = ROOT / "media" / "stage" / "eyes" / "latest.jpg"
        eye_img = f'<img src="media/stage/eyes/latest.jpg?t={int(datetime.now().timestamp())}" alt="latest eye" style="max-width:100%;border-radius:12px;border:2px solid #3ddc84"/>'
    else:
        eye_img = "<p style='color:#888'>No latest eye frame yet \u2014 run eyes.py start</p>"

    cams_html = "".join(f"<li>{c.replace('**','').replace('`','')}</li>" for c in cams)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta http-equiv="refresh" content="15"/>
<title>OUR WORLD \u00b7 Home</title>
<style>
  body {{ font-family: system-ui, Segoe UI, sans-serif; background:#0d1117; color:#e6edf3; margin:0; padding:24px; }}
  h1 {{ margin:0 0 8px; font-weight:700; letter-spacing:0.02em; }}
  .sub {{ color:#8b949e; margin-bottom:24px; }}
  .grid {{ display:grid; grid-template-columns: 1.2fr 1fr; gap:20px; }}
  @media (max-width:900px) {{ .grid {{ grid-template-columns:1fr; }} }}
  .card {{ background:#161b22; border:1px solid #30363d; border-radius:16px; padding:18px 20px; }}
  .badge {{ display:inline-block; padding:4px 10px; border-radius:999px; background:{eye_color}22; color:{eye_color}; font-weight:600; font-size:14px; }}
  h2 {{ font-size:15px; text-transform:uppercase; letter-spacing:0.08em; color:#8b949e; margin:0 0 12px; }}
  ul {{ margin:0; padding-left:18px; line-height:1.55; }}
  a {{ color:#58a6ff; }}
  .pulse {{ font-size:13px; color:#8b949e; margin-top:16px; }}
</style>
</head>
<body>
  <h1>OUR WORLD</h1>
  <div class="sub">Architect01 \u00d7 Grok \u00b7 I do \u00b7 {local}</div>
  <div class="grid">
    <div class="card">
      <h2>Clear eyes \u00b7 PC</h2>
      <p><span class="badge">{eye_status}</span></p>
      {eye_img}
    </div>
    <div class="card">
      <h2>House cameras</h2>
      <ul>{cams_html}</ul>
      <h2 style="margin-top:20px">Shield \u00b7 Sword</h2>
      <ul>
        <li>True-love circle \u2014 vault (names as spoken)</li>
        <li>Shield \u00b7 sword \u00b7 clear eyes \u2014 Art. 13</li>
        <li>Next sword tip: original #2 link</li>
      </ul>
      <h2 style="margin-top:20px">Next</h2>
      <ul>
        <li>Link original Eufy #2</li>
        <li>True-love names when ready</li>
        <li>Keep eyes on</li>
      </ul>
    </div>
  </div>
  <p class="pulse">Auto-refresh 15s \u00b7 home_status.py \u00b7 great intent \u00b7 house law</p>
</body>
</html>
"""
    OUT_HTML.write_text(html, encoding="utf-8")

    if HUB.exists():
        shutil.copy2(OUT_MD, HUB / "HOME-STATUS.md")
        shutil.copy2(OUT_HTML, HUB / "HOME-STATUS.html")
        if EYES_LATEST.exists():
            eyes_hub = HUB / "eyes"
            eyes_hub.mkdir(exist_ok=True)
            shutil.copy2(EYES_LATEST, eyes_hub / "latest.jpg")

    return OUT_MD, OUT_HTML


def main(argv: list[str]) -> int:
    md, html = build()
    print(f"wrote {md}")
    print(f"wrote {html}")
    if argv and argv[0] in ("open", "show", "view"):
        webbrowser.open(html.as_uri())
        print("opened browser")
    return 0


if __name__ == "__main__":
    import sys

    raise SystemExit(main(sys.argv[1:]))
